config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root "static_pages#home"
  get  "/signup",  to: "employees#new"
  get    "/login",   to: "sessions#new"
  post   "/login",   to: "sessions#create"
  delete "/logout",  to: "sessions#destroy"
  patch "/attendances",  to: "attendances#create"
  resources :employees
  resources :attendances,          only: [:new, :create, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :employee
  default_scope -> { order(:start_work_date) }
  validates :employee_id, presence: true
  validates :break_time, presence: true, numericality: {greater_than_or_equal_to: 0}
end

app/models/employee.rb
class Employee < ApplicationRecord
  has_many :attendances, dependent: :destroy
  before_save { self.email = email.downcase }
  validates :hourly_wage, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 0}
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  
  # 渡された文字列のハッシュ値を返す
  def Employee.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

  private

    # beforeフィルタ

    # ログイン済みemployeeかどうか確認
    def logged_in_employee
      unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to login_url, status: :see_other
      end
    end

    # adminemployeeかどうか確認
    def admin_employee
      if current_employee.admin_flag != 1
        flash[:danger] = "この操作の権限がありません。"
        redirect_to employees_path, status: :see_other
      end
    end

    def admin_or_current
      if current_employee.admin_flag != 1 && current_employee.id != params[:id].to_i
        flash[:danger] = "この操作の権限がありません。"
        redirect_to employees_path, status: :see_other
      end
    end
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :logged_in_employee, only: [:new, :create, :edit, :update, :destroy]
  before_action :admin_employee, only: [:edit, :update, :destroy]

  def new
    if current_employee.attendance_flag == 0
      @attendance = current_employee.attendances.build
    else
      @attendance = Attendance.where(employee_id: current_employee.id).last
    end
  end
  
  def create
    if current_employee.attendance_flag == 0
      @attendance = current_employee.attendances.build(attendance_params_start)
      attendanceFlagParam = {attendance_flag: 1}
      if @attendance.save && current_employee.update(attendanceFlagParam)
        flash[:success] = "勤怠を登録しました。"
        redirect_to current_employee
      else
        render 'new', status: :unprocessable_entity
      end
    else
      @attendance = Attendance.where(employee_id: current_employee.id).last
      attendanceFlagParam = {attendance_flag: 0}
      if current_employee.update(attendanceFlagParam) && @attendance.update(attendance_params_end)
        flash[:success] = "勤怠を登録しました。"
        redirect_to current_employee
      else
        render 'new', status: :unprocessable_entity
      end
    end
  end

  def edit
    @attendance = Attendance.find(params[:id])
  end

  def update
    @attendance = Attendance.find(params[:id])
    if @attendance.update(attendance_params_edit)
      flash[:success] = "勤怠情報更新"
      redirect_to employee_path(@attendance.employee_id)
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    @attendance = Attendance.find(params[:id]).destroy
    flash[:success] = "勤怠の削除に成功しました"
    redirect_to employee_path(@attendance.employee_id), status: :see_other
  end

  private

    def attendance_params_start
      params.require(:attendance).permit(:start_work_date)
    end

    def attendance_params_end
      params.require(:attendance).permit(:break_time, :end_work_date)
    end

    

    def attendance_params_edit
      params.require(:attendance).permit(:start_work_date, :break_time, :end_work_date, :attendance_modify_flag)
    end

end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :logged_in_employee, only: [:index, :show, :edit, :update, :destroy]
  before_action :admin_employee, only: [:edit, :update, :destroy]
  before_action :admin_or_current, only: [:show]

  def index
    @employees = Employee.order("id asc").paginate(page: params[:page])
  end

  def show
    @year = params["date(1i)"] || Date.today.year
    @month = params["date(2i)"] || Date.today.month
    @year = @year.to_i
    @month = @month.to_i
    @employee = Employee.find(params[:id])
    @attendances = @employee.attendances.where(start_work_date: Date.new(@year,@month,1)..Date.new(@year,@month,1).next_month)
    @all_work_time = 0
    @attendances.each do |attendance|
      if attendance.end_work_date != nil
        @all_work_time += attendance.end_work_date - attendance.start_work_date
      end
    end
    @all_work_time /= 3600
  end

  def new
    @employee = Employee.new
  end

  def create
    @employee = Employee.new(employee_params)
    if @employee.save
      reset_session
      log_in @employee
      flash[:success] = "こんにちは！"
      redirect_to @employee
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def edit
    @employee = Employee.find(params[:id])
  end

  def update
    @employee = Employee.find(params[:id])
    if @employee.update(employee_params_edit)
      flash[:success] = "情報更新"
      redirect_to @employee
    else
      render 'edit', status: :unprocessable_entity
    end
  end

  def destroy
    Employee.find(params[:id]).destroy
    flash[:success] = "削除に成功しました"
    redirect_to employees_url, status: :see_other
  end

  private

    def employee_params
      params.require(:employee).permit(:name, :email, :password,
                                   :password_confirmation)
    end

    def employee_params_edit
      params.require(:employee).permit(:name, :email, :hourly_wage)
    end
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    employee = Employee.find_by(email: params[:session][:email].downcase)
    if employee && employee.authenticate(params[:session][:password])
      reset_session      # セッション固定対策
      log_in employee
      redirect_to employee
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new', status: :unprocessable_entity
    end
  end

  def destroy
    log_out
    redirect_to root_url, status: :see_other
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  # ページごとの完全なタイトルを返す
  def full_title(page_title = '')
    base_title = "cafeFree App"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/hello_codespaces_helper.rb
module HelloCodespacesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  # 渡されたemployeeでログインする
  def log_in(employee)
    session[:employee_id] = employee.id
  end

  # 現在ログイン中のemployeeを返す（いる場合）
  def current_employee
    if session[:employee_id]
      @current_employee ||= Employee.find_by(id: session[:employee_id])
    end
  end

  # employeeがログインしていればtrue、その他ならfalseを返す
  def logged_in?
    !current_employee.nil?
  end

  # 現在のemployeeをログアウトする
  def log_out
    reset_session
    @current_employee = nil   # 安全のため
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/attendances/_attendance.html.erb
<li id="attendance-<%= attendance.id %>">
  <span class="attendance"><%= attendance.start_work_date.mday %>日  <%= attendance.start_work_date.strftime('%H:%M') %>~<%= attendance.end_work_date.blank? ? "" : attendance.end_work_date.strftime('%H:%M') %> 休憩時間:<%= attendance.break_time %>時間 <span class="badge"><%= attendance.attendance_modify_flag == 1 ? "修正済み" : "" %></span></span>

  <% if current_employee.admin_flag == 1 %>
    <%= link_to "勤怠修正", edit_attendance_path(attendance) %>
  <% end %>
</li>

app/views/attendances/edit.html.erb
<% provide(:title, "Edit attendance") %>
<%= link_to "勤怠一覧へ", employee_path(@attendance.employee_id) %>
<h1>勤怠情報編集</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @attendance) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.hidden_field :attendance_modify_flag, :value => 1 %>
      <%= f.label :start_work_date, "出勤時間" %>
      <%= f.datetime_field :start_work_date, class: 'form-control' %>

      <%= f.label :break_time, "休憩時間" %>
      <%= f.number_field :break_time, step: "0.1", class: 'form-control' %>

      <%= f.label :end_work_date, "退勤時間" %>
      <%= f.datetime_field :end_work_date, class: 'form-control' %>

      <%= f.submit "更新", class: "btn btn-primary" %>
    <% end %>
    <div>
      <span class="attendance-delete badge text-bg-danger"><%= link_to "勤怠を削除", @attendance, data: { "turbo-method": :delete,
                                          turbo_confirm: "本当に削除しますか" } %></span>
    </div>
  </div>
</div>

app/views/attendances/new.html.erb
<% provide(:title, "New attendance") %>
<%= link_to "勤怠一覧へ", current_employee %>
<h1>勤怠入力</h1>
<h2 id="clock"></h2>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @attendance,  url: {controller: 'attendances', action: 'create' }) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <% if current_employee.attendance_flag == 0 %>
        <%= f.hidden_field :start_work_date, :value => Time.now %>
        <%= f.submit "出勤", class: "btn btn-primary" %>
      <% else %>
        <%= f.label :break_time, "休憩時間" %>
        <%= f.number_field :break_time, step: "0.1", class: 'form-control' %>

        <%= f.hidden_field :end_work_date, :value => Time.now %>
        <%= f.submit "退勤", class: "btn btn-primary" %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/employees/_employee.html.erb
<tr>
  <td><%= employee.id%></td>
<% if current_employee == employee || current_employee.admin_flag == 1 %>
  <td><%= link_to employee.name, employee %></td>
<% else %>
  <td><%= employee.name %></td>
<% end %>
<% if employee.attendance_flag == 1 %>
  <td><span class="badge text-bg-primary">出勤中</span></td>
<% else %>
  <td></td>
<% end %>
<% if employee.admin_flag == 1%>
  <td><span class="badge text-bg-danger">管理者</span></td>
<% else %>
  <td></td>
<% end %>
<% if current_employee.admin_flag == 1%>
  <td><span class="employee-edit badge"><%= link_to "従業員情報編集", edit_employee_path(employee) %></span></td>
<% else %>
  <td></td>
<% end %>

</tr>

app/views/employees/edit.html.erb
<% provide(:title, "Edit employee") %>
<%= link_to "従業員一覧へ", employees_path %>
<h1>従業員情報編集</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @employee) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name, "名前" %>
      <%= f.text_field :name, readonly: true, class: 'form-control' %>

      <%= f.label :email, "Eメール" %>
      <%= f.email_field :email, readonly: true, class: 'form-control' %>

      <%= f.label :hourly_wage, "時給" %>
      <%= f.number_field :hourly_wage, class: 'form-control' %>

      <%= f.submit "更新", class: "btn btn-primary" %>
    <% end %>
    <% if @employee.admin_flag != 1 %>
      <div>
        <span class="employee-delete badge text-bg-danger"><%= link_to "従業員を削除", @employee, data: { "turbo-method": :delete,
                                           turbo_confirm: "本当に削除しますか" } %></span>
      </div>
    <% end %>
  </div>
</div>

app/views/employees/index.html.erb
<% provide(:title, 'All employees') %>
<h1>従業員一覧</h1>
<%= will_paginate %>
<table class="table">
  <thead>
    <tr>
      <th scope="col">従業員ID</th>
      <th scope="col">名前</th>
      <th scope="col">出勤状態</th>
      <th scope="col"></th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% @employees.each do |employee| %>
      <%= render employee %>
    <% end %>
  </tbody>
</table>

app/views/employees/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>新規登録</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @employee) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "アカウント発行", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/employees/show.html.erb
<% provide(:title, @employee.name) %>
<div class="row">
  <aside class="col-md-4">
    <%= link_to "従業員一覧へ", employees_path %>
    <section class="employee_info">
      <h1>
        <%= @employee.name %>
      </h1>
      <h2><%= @year %>年</h2>
      <h2>時給 : <%= @employee.hourly_wage %> 円</h2>
      <h2><%= @month %>月の総労働時間 : <%= @all_work_time %> 時間</h2>
      <h2><%= @month %>月の給料 : <%= (@all_work_time * @employee.hourly_wage).to_i %> 円</h2>
    </section>
  </aside>
  <div class="col-md-5">
    <% if @employee.attendances.any? %>
      <h3>勤怠実績</h3>
        <%= form_with url: employee_path(@employee), method: :get do |f| %>
          <%= f.date_select(:date, discard_day: true) %>
          <%= f.submit "検索" %>
        <% end %>
      <ul class="attendances">
        <%= render @attendances %>
      </ul>
    <% end %>
  </div>
  <div class="col-md-3">
    <% if current_employee.id == @employee.id %>
      <td><span class="attendance-new badge text-bg-greeen"><%= link_to "勤怠管理", new_attendance_path %></span></td>
    <% end %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Create
    by Rohan Kid</a>
  </small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "cafeFree app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "ホーム",   root_path %></li>
        <% if logged_in? %>
          <li>
            <%= link_to "ログアウト", logout_path,
                                    data: { "turbo-method": :delete } %>
          </li>
        <% else %>
          <li><%= link_to "ログイン", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>cafeFree App</h1>

  <%= link_to "新規登録へ", signup_path, class: "btn btn-lg btn-primary" %>
</div>